apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: blockchaine-cluster
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
  extraPortMappings:
  - containerPort: 30045
    hostPort: 30045
    protocol: TCP
